#!/usr/bin/env node
var nomnom = require('nomnom');

nomnom.script('blogbot').nocolors()
nomnom.command('serve')
  .help('Starts the blogbot server.')
  .options({
    rpcport: {
      help: 'Sets the port for the rpc server.',
      default: 2000
    },
    httpport: {
      help: 'Sets the port for the rpc server.',
      default: 8000
    }
  })
  .callback(require('./lib/index').start)
nomnom.command('repl')
  .help('Starts a repl that connects to the given scuttlebot\'s RPC channel.')
  .options({
    host: {
      help: 'Hostname of the scuttlebot.',
      default: 'localhost'
    },
    port: {
      help: 'Port of the scuttlebot.',
      default: 2000
    }
  })
  .callback(require('./lib/index').repl)
nomnom.parse();